<?xml version="1.0" encoding="utf-8"?><Database Name="PhanTichComment" Class="KetQuaPhanTichDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LAPTOP-8I0O1JHC\SQLEXPRESS;Initial Catalog=PhanTichComment;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="PhanTichCommentConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.KetQuaPhanTich" Member="KetQuaPhanTiches">
    <Type Name="KetQuaPhanTich">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NoiDung" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="KetQua" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
</Database>